---
keys:
  - 'AIzaSyCQMtoOPkxOmiIhzanjOfSj8Aco6uXHd9w'
  - 'AIzaSyDrOhGpXNwe5n4-xeTrcWsEYrDA5xE0JH0'
  - 'AIzaSyCYh06Uv-hHWBAB2rbWSdFmfyzY7SDLT4U'
  - 'AIzaSyA_8uNN5X5OAFIfJ_Pov_Qerv1-gwTMEDk' 

urls:
  staticMap: 'https://maps.googleapis.com/maps/api/staticmap'
  elevation: 'https://maps.googleapis.com/maps/api/elevation/json'

filetree:
  config: 'config.yaml'
  preview: 'quicklook.png'
  rezpreview: 'resolution.png'
  rawdir: 'raw'
  maptilesdir: 'maptiles'
  slicedir: 'slices'
  vectordir: 'vectors'

mapOptions:
  maptype: "road"
  scale: 2
  size: "320x320"

max_samples_per_request: 512

useCache: 1

blankStyle:
  elementType: all
  featureType: all
  stylers:
  - visibility: 'off'

...