---
keys:
  - 'AIzaSyCQMtoOPkxOmiIhzanjOfSj8Aco6uXHd9w'
  - 'AIzaSyDrOhGpXNwe5n4-xeTrcWsEYrDA5xE0JH0'
  - 'AIzaSyCYh06Uv-hHWBAB2rbWSdFmfyzY7SDLT4U'
  - 'AIzaSyA_8uNN5X5OAFIfJ_Pov_Qerv1-gwTMEDk' 

urls:
  staticMap: 'https://maps.googleapis.com/maps/api/staticmap'
  elevation: 'https://maps.googleapis.com/maps/api/elevation/json'

errorHash: '9bbe3528194a37629b9b8836c6b9a441'

filetree:
  config: 'config.yaml'
  elevpreview: 'quicklook.png'
  rezpreview: 'resolution.png'
  rawdir: 'raw'
  maptilesdir: 'maptiles'
  slicedir: 'slices'
  vectordir: 'vectors'
  rezdir: 'resoltions'

mapOptions:
  maptype: "road"
  scale: 1
  size: "640x640"

max_samples_per_request: 512
max_requests_per_day: 25000

useCache: True

...